### ISSUE TITLE
Multi-library support

### ISSUE THREAD

**Issue by jeremyadamsfisher** [simonlevine/bioinformatics-project#30]
Need some way to handle something like:
```yaml
sequence_files_R1: 
- "data/raw/reads/lib1_R1.fastq"
- "data/raw/reads/lib2_R1.fastq"
sequence_files_R2: 
- "data/raw/reads/lib1_R2.fastq"
- "data/raw/reads/lib2_R2.fastq"
```
Currently, this would crash...
